apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
  labels:
    app: example
spec:
  template:
    metadata:
      name: pod-my-nginx
      labels:
        env: production
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.14.2
  selector:
    matchLabels:
      env: production
  strategy:
    type: Recreate
  replicas: 5
